global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "user-service"
    static_configs:
      - targets: ["user-service:3001"]

  - job_name: "post-service"
    static_configs:
      - targets: ["post-service:3002"]

  - job_name: "interaction-service"
    static_configs:
      - targets: ["interaction-service:3003"]

  - job_name: "notification-service"
    static_configs:
      - targets: ["notification-service:3004"]
